{
  menuItems {
    nodes {
      label
      parentDatabaseId
      databaseId
      linkRelationship
      connectedObject {
        ... on Page {
          pageId
          slug
        }
      }
    }
  }
}
